### ISSUE TITLE
How to run SuperCaustics on NvRTX UE4.26-Caustics

### ISSUE THREAD

**Issue by Daiqy** [MMehdiMousavi/SuperCaustics#3]
Hi @MMehdiMousavi ! I meet some questions when trying to use SuperCaustics. 
After I finish compiling UE4 following [NvRTX instruction](https://github.com/NvRTX/UnrealEngine/tree/NvRTX_Caustics-4.26), I am wondering how I can start running SuperCaustics project files on it. Should I rebuild AIP_nVRTX, or move some files from SuperCaustics directory to UE4 install directory? 
Could you give some guidance? Thanks!

**Comment by MMehdiMousavi** [comment]
Hi! the message youre getting is likely because your editor version is 4.26.2 or higher. 
SuperCaustics 1.00 was made with 4.26.1 so your engine version is different. 

there are two ways to solve this, one is open the .uproject file with notepad, and change the version number to your editors version. this is a hacky way to do it but probably should work fine. 

If that doesn't work, you can follow instructions [here](https://forums.unrealengine.com/t/solved-upgrade-c-project-from-ue-4-24-to-4-25-under-linux/144950/6) to upgrade and rebuild the project again.

**Comment by MMehdiMousavi** [comment]
If i misunderstood your question, let me know. if you were asking how to actually run the project, you do that by opening the .uproject file inside the Supercaustics folder.

**Comment by Daiqy** [comment]
Thank you very much! I have solved the problem and succeeded in running the project now.

**Comment by Daiqy** [comment]
Another problem is about the probe data gatherer. Before I run [Probe.py](https://github.com/MMehdiMousavi/SuperCaustics/blob/main/Probe/Probe.py), should I copy the [Prob floder](https://github.com/MMehdiMousavi/SuperCaustics/tree/main/Probe) to the Supercaustics folder at first? And are there any additional settings?
Thanks again!

**Comment by MMehdiMousavi** [comment]
Hi again! 
Probe is a separate system of its own and only sends key commands to the game window. 

Just run the python file, and make sure you give it the correct window handle.
Also be sure to set the resolution to your desired final resolution since the `c` command takes screenshot at your current resolution. 

When you run probe, be sure to check for your Frame rate (you can turn it on using the `statFPS` Console command) , and adjust the wait times in the script accordingly (if you have low FPS, you should typically wait more between actions). The reason is that the Raytracing denoiser works temporally, and it can take a couple frames for it to denoise the image. 

let me know if you have any more questions, ill be happy to help.

**Comment by MMehdiMousavi** [comment]
Also, before you run things for real, make sure to delete any left-over test screenshots from your screenshots folder, so you can later process it much easier. 
screenshots are saved at `supercaustics folder>saved>screenshots>windows>`

**Comment by Daiqy** [comment]
Thanks for your help! I have run the Probe.py. 
But regarding the keyboard shortcuts, like ["U"](https://github.com/MMehdiMousavi/SuperCaustics/blob/54f3b71a002abe5e2565df015b237dea9d8bea3d/Probe/Probe.py#L65), ["V"](https://github.com/MMehdiMousavi/SuperCaustics/blob/54f3b71a002abe5e2565df015b237dea9d8bea3d/Probe/Probe.py#L73) in Probe.py, and from ["c"](https://github.com/MMehdiMousavi/SuperCaustics/blob/54f3b71a002abe5e2565df015b237dea9d8bea3d/Probe/Probe_utils.py#L38) to ["d"](https://github.com/MMehdiMousavi/SuperCaustics/blob/54f3b71a002abe5e2565df015b237dea9d8bea3d/Probe/Probe_utils.py#L60) in Probe_utils.py. It seems that those are not the default shortcuts settings in Unreal editor. 
Could you give me some explanations of what they mean in Unreal editor respectively? So that I can set them in "Edit - (Configuration) - Editor Preferences - (General) - Keyboard Shortcuts".
Thanks!

**Comment by Daiqy** [comment]
Thanks for your help! I have run the Probe.py.
When I check the captured rendered image (the following pictures), I find that the caustics in the image are not sharp enough as shown in the paper. I have tried to adjust the position of the light source, but no significant improvement. Can I adjust some other parameters to control the caustics? 
![HighresScreenshot00002](https://user-images.githubusercontent.com/26495036/132981340-856569dd-dc51-45f1-924a-6929db2702cc.png)
![HighresScreenshot00003](https://user-images.githubusercontent.com/26495036/132981357-52970a42-7f20-4380-b6c4-b72631b25910.png)

**Comment by MMehdiMousavi** [comment]
Hi! 
To make the _shadows_ soft, you can adjust the `source angle` in Light Manager's `light` tab inside the details panel. 
To change the softness of the caustics, make sure to click on the `directional light component` inside the component viewer, then scroll down to `Ray Tracing` section. From there, you can adjust all the settings below: 
[![softness.jpg](https://i.postimg.cc/Ssry96FH/softness.jpg)](https://postimg.cc/cgvyy8Jc)
caustics precision, Softness, Range, etc.

**Comment by Daiqy** [comment]
Thanks again, I have solved the problems with your great help!
